

SELECT
  'DRC' AS `organization`,
  'aou-datawarehouse-sandbox' AS `database`,
  'ppi_001' AS `schema`,
  'DRC-PPI' AS `source_system_default`,
  'DRC PPI' AS `site_default`,
  'BigQuery' AS `data_transfer_type_default`,
  'America/New_York' AS `timezone_default`,
  True AS `static_dataset`,
  '2009-10-01' AS `earliest_date`,
  '2019-09-23' AS `latest_date`,
  12 AS `months_history`,
  90 AS `length_of_stay_cap`,
  
    [ '' ]
     AS `null_values`,
  False AS `persist_all_metric_executions`,
  'all_patients' AS `cohort`,
  'today' AS `cohort_snapshot_date`,
  'True' AS `drop_metric_tables`,
  CONCAT(
    'https://lookerstudio.google.com/reporting/create?',
    'c.reportId=', '2de086de-b4ab-4431-8786-57ffa47e96b8','&ds.mbdd.type=TABLE',
    '&ds.mbdd.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.mbdd.datasetId=', 'mv2451_ppi_001',
    '&ds.mbdd.tableId=', 'metric_by_day_dimensions','&ds.mbd.type=TABLE',
    '&ds.mbd.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.mbd.datasetId=', 'mv2451_ppi_001',
    '&ds.mbd.tableId=', 'metric_by_day','&ds.mo.type=TABLE',
    '&ds.mo.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.mo.datasetId=', 'mv2451_ppi_001',
    '&ds.mo.tableId=', 'metric_overall','&ds.md.type=TABLE',
    '&ds.md.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.md.datasetId=', 'mv2451_ppi_001',
    '&ds.md.tableId=', 'metric_definition','&ds.ftl.type=TABLE',
    '&ds.ftl.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.ftl.datasetId=', 'mv2451_ppi_001',
    '&ds.ftl.tableId=', 'fhir_table_list','&ds.pv.type=TABLE',
    '&ds.pv.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.pv.datasetId=', 'mv2451_ppi_001',
    '&ds.pv.tableId=', 'project_variables','&ds.mel.type=TABLE',
    '&ds.mel.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.mel.datasetId=', 'mv2451_ppi_001',
    '&ds.mel.tableId=', 'metric_execution_log','&ds.mt.type=TABLE',
    '&ds.mt.projectId=', 'aou-datawarehouse-sandbox',
    '&ds.mt.datasetId=', 'mv2451_ppi_001',
    '&ds.mt.tableId=', 'metric_thresholds'
  ) AS looker_studio_url